// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-Uk6IW54nMvBgxX7CPsgx0lMo58otfQ',
    appId: '1:163954857780:web:60fbaf5d9cb54115ae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    authDomain: 'devfestlagos-2022.firebaseapp.com',
    storageBucket: 'devfestlagos-2022.appspot.com',
    measurementId: 'G-CR8TKECQD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyucrDWB2TK6bLcne65YcihOBVBHLjMtI',
    appId: '1:163954857780:android:8f28e8d1eac80d7cae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    storageBucket: 'devfestlagos-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjQGvrhDQTdVk5-DInHkDLMiOgvzHoxI',
    appId: '1:163954857780:ios:e9c87dee27844b2cae3761',
    messagingSenderId: '163954857780',
    projectId: 'devfestlagos-2022',
    storageBucket: 'devfestlagos-2022.appspot.com',
    androidClientId: '163954857780-4o1eqfetdrv3j6u6lc8ke1ik6ksv1cqs.apps.googleusercontent.com',
    iosClientId: '163954857780-u8p3v1ug6scdo4n91l56ooesm3q9u6in.apps.googleusercontent.com',
    iosBundleId: 'com.gdglagos.devfestlg',
  );
}
